### PR TITLE
Feat: Add documentation for `Azure Resource ID` configuration

### PR DESCRIPTION
**Pull request by ctlong**
Document the new configuration options resulting from the effort to include the `x-ms-AzureResourceId` header in post requests to the azure log handling service.

[#178417450](https://www.pivotaltracker.com/story/show/178417450)

### CODE REVIEW

**Comment by ctlong** [comment]
screen-shot

**Comment by paigecalvert** [comment]
Thank you @ctlong! This looks great. I'm seeing that this is still marked as a "work in progress". Should I hold off on merging?

**Comment by ctlong** [comment]
This PR is blocked in order to sync up with an upcoming azure nozzle release.

**Review by mjj209 — APPROVED** [review]
Looks great!

**Comment by paigecalvert** [comment]
Thank you!

**Pull request merged**
