### PR TITLE
Add release note for v4.0.8

### PR DESCRIPTION
**Pull request by rroberts2222**

### CODE REVIEW

**Comment by anita-flegg** [comment]
@HenryBorys , FYI -- not sure if this belongs to one of your services

**Comment by HenryBorys** [comment]
@anita-flegg This isn't a TAS Service. I don't recognize it. Not sure who is working on this. @acrmp Do you normally work with a writer? If so, who? Thanks.

**Comment by acrmp** [comment]
@HenryBorys For updating the release notes we typically just make a PR, not aware of a time where we've needed to work more closely with a tech writer for this product.

**Comment by HenryBorys** [comment]
@anita-flegg Looking at past commits, it appears you are the only writer that has been routinely active on this repo.

**Comment by anita-flegg** [comment]
@acrmp, Let me know if you need help releasing the latest docs.

**Pull request merged**
